approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

npmAuthToken: "${NPM_TOKEN:-fallback}"

npmMinimalAgeGate: 0

npmPublishRegistry: "https://registry.npmjs.org"

yarnPath: .yarn/releases/yarn-4.17.1.cjs
