# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'sample-app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sample-app
  pod 'JudoKitObjC'

  target 'sample-appTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
