export enum TestData {
  CARD_NUMBER = '4976 3500 0000 6891',
  FAILED_CARD_NUMBER = '4111 1111 1111 1111',
  CARDHOLDER_NAME = 'Test User',
  EXPIRY_DATE = '1225',
  SECURITY_CODE = '341',
  DECLINED_CODE = '123',
  PAY_WITH_TOKEN = 'PAY WITH TOKEN',
  PAY_WITH_PREAUTH_TOKEN = 'PREAUTH WITH TOKEN',
  FRICTIONLESS = 'Frictionless Successful',
  FRICTIONLESS_NOMETHOD = 'Frictionless NoMethod',
  FRICTIONLESS_AUTHFAILED = 'Frictionless AuthFailed',
}

export enum Selectors {
  SETTINGS_BUTTON = 'settings-button',
  JUDO_ID_INPUT = 'judo-id-input',
  AUTH_TOGGLE = 'using-token-and-secret-toggle',
  TOKEN_INPUT = 'token-input-field',
  SECRET_INPUT = 'secret-input-field',
  BACK_BUTTON = 'back-button',
  CARD_NUMBER_INPUT = 'Card Number Field',
  CARDHOLDER_NAME_INPUT = 'Cardholder Name Field',
  EXPIRY_DATE_INPUT = 'Expiry Date Field',
  SECURITY_CODE_INPUT = 'Security Code Field',
  THREEDS2_COMPLETE_BUTTON = 'COMPLETE',
  THREEDS2_SCREEN_HEADER = 'SECURE CHECKOUT',
  PAY_NOW_BUTTON = 'Submit Button',
  PAY_WITH_CARD = 'Pay with card',
  PAY_WITH_PREAUTH = 'Pre-auth with card',
  REGISTER_CARD = 'Register card',
  CHECK_CARD = 'Check card',
  SAVE_CARD = 'Save card',
  PAYMENT_METHODS = 'Payment methods',
  PREAUTH_METHODS = 'PreAuth methods',
  ADD_CARD_BUTTON = 'ADD CARD',
  EXISTING_CARD = 'Visa Ending 6891 ',
  TOKEN_PAYMENTS = 'Token Payments',
  TOKENIZE_NEW_CARD = 'TOKENIZE A NEW CARD',
  TOKEN_CVV_CODE = 'card-token-security-code',
  FEATURE_LIST = 'home-screen-section-list',
  TOKEN_SCROLL_VIEW = 'token-scroll-view',
  PAY_WITH_TOKEN = 'pay-with-token-button',
  PREAUTH_WITH_TOKEN = 'preauth-with-token-button',
  CHALLENGE_REQUEST_SETTINGS = 'Challenge request indicator',
  NO_PREFERENCE = 'No preference',
  HELPER_TEXT = 'help-steps-list',
}

export enum UserFeedback {
  THREEDS2_CANCELLED = 'Unable to process transaction. Card authentication failed with 3DS Server.',
}
