name: iOS Build and Test Sample Apps

on:
  pull_request:
jobs:
  build_and_test_sample_apps:
    uses: Judopay/github-actions/.github/workflows/ios-build-and-test-sample-apps.yml@master
    secrets: inherit
  test_sample_apps_simulator:
    uses: Judopay/github-actions/.github/workflows/ios-test-sample-apps-simulator.yml@master
    needs: build_and_test_sample_apps
    secrets: inherit
