on:
  push:
    branches:
      - master

jobs:
  snyk-scan:
    uses: Judopay/github-actions/.github/workflows/snyk-scan.yml@master
    secrets:
      snyk-token: ${{ secrets.SNYK_AUTH_TOKEN }}
      maven-gcp-credentials: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY_BASE64 }}
